### ISSUE TITLE
对于非匿名调查，调查发起人有权限查看每个人的答案

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#102]
1. 发起一个survey，等待用户作答。
2. 进入答案统计页面的“See Participation” Tab页中，点击其中某个参与人员的link查看其答案，结果报401异常。

这种情况不应该报401异常。非匿名的survey发起人应该有权限查看每个人的答案。

**Comment by LiuSiHeng** [comment]
fixed
