### ISSUE TITLE
“我发起的调查”的查看功能完善

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#15]
点击“我发起的调查”页面中，某一个survey的“查看”link，进入该页面。
当前这个页面上的信息过于简单，需增加：
1： paper的link，点击这个paper 的link，跳转到paper的detail页面
2： 增加一个参与调查的人的列表，
列表包括：
个人信息（姓名， email等）， 答题时间，是否完成
3. 增加一个“提醒交卷”的button 和“提醒内容”的文本框，对于那些还未交卷的人。填写提醒信息，并且点击“提交交卷”button后，会发送一封提醒邮件给所有为提交的用户。邮件内容应包含这个调查的url

**Comment by gongbf** [comment]
Complete
