### ISSUE TITLE
切换到prod环境，并确保prod环境能运行成功

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#28]
在本地，把web.xml中的spring.profiles.default参数改为production

即切换到prod环境，也就是切换到mysql db了。
此时用到的数据源为：
src\main\resources\applicationContext.xml中配置的：
	    <bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">  
	        <property name="jndiName">  
	            <value>java:comp/env/jdbc/mysurvey</value>  
	        </property>  
	    </bean> 

做这个task的时候，需要在tomcat里面配置一个jdbc/mysurvey的JNDI，该JNDI指向
https://github.com/microlcl/mysurvey/issues/27 中用到的mysql数据库。

然后运行程序，看看有无问题。

**Comment by LiuSiHeng** [comment]
为了不影响其他人merge之后的测试， 测试本功能需手动修改web.xml 中的 spring.profiles.default参数改为production。 启动tomcat时可能会因为初始化项目过多，启动超时导致tomcat sever启动错误。可以手动修改tomcat的timeout值。

**Comment by microlcl** [comment]
Good Job! SiHeng
