### ISSUE TITLE
完成页面国际化

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#37]
我昨晚了login登录页面和菜单的国际化，剩下的页面也需要国际化：
系统会根据游览器默认语言展示中文或英文
做的时候的要点：
1：先把需要显示的文字记录在：message.properties里面
2： 在要国际化的jsp页面，增加tag标签申明：
<%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
然后在现实文字的地方，用类似spring:message code="menu.admin.role"/>来代替
3: 对于java后台需要访问message.properties的情况，可以参照LoginController.java里面的进行相应处理
RequestContext requestContext = new RequestContext(request);
String errorMsg = requestContext.getMessage("login.error")
3： message.properties完成后，把里面的内容copy到message_en_US.properties
4: 编写相应的message_en_US.properties文件：直接在eclispe里面打开这个文件，然后输入中文，eclipse会自动编码的。

**Comment by microlcl** [comment]
继续完成国际化。

**Comment by microlcl** [comment]
登录页面什么都不填写，直接sign in，错误提示消息还是中文。

**Comment by LiuSiHeng** [comment]
fixed

**Comment by microlcl** [comment]
“我参与的调查”的list页面中，Survey Status列显示的vlaue是中文。

**Comment by microlcl** [comment]
发布一个survey成功后，提示信息是中文
