### ISSUE TITLE
调查结果导出为Excel

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#42]
在Answer Statistics 的Tab页里面，增加一个'Export'的button，点击此button，能够把这个调查的答案导出成一个excel格式的文件并下载。
excel的格式按照上次Jacky开会时说的做：
1: 只有选择题才能导出答案
2： 第一行为题目，每个题目和选项共占据一格，比如有十个题目，那么excel的第一行就有10列，每列里面的内容就是“题目 + 选项”
3： 接下来的每一行为调查人员的答案，一个人的答案占据一行

如又任何疑问，随时ping我

**Comment by microlcl** [comment]
导出excel采用Apache的POI来做：
http://poi.apache.org/

这里有一段产生excel的代码供参考：

package com.eastteam.myprogram.entity;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;

import com.eastteam.myprogram.web.scheme.SchemeProductContainer;
/**
 * 导出Excel文档工具类
 * @author ydq
 * */
public class ExcelUtil {
 
    /**
     * 创建excel文档，
     * @param map 数据
     * */
    public static Workbook createWorkBook(Map<String, Object> map) {
    	Scheme scheme = (Scheme) map.get("scheme");
    	List<SchemeProductContainer> schemeProdCtrs = (List<SchemeProductContainer>) map.get("schemeProdCtrs");
    	BigDecimal totalPrice = (BigDecimal) map.get("totalPrice");
    	
        // 创建excel工作簿
        Workbook wb = new HSSFWorkbook();
        // 创建第一个sheet（页），并命名
        Sheet sheet = wb.createSheet(scheme.getName());
        //设置列宽
        sheet.setColumnWidth((short) 0, 5*256);
        sheet.setColumnWidth((short) 1, 15*256);
        sheet.setColumnWidth((short) 2, 15*256);
        sheet.setColumnWidth((short) 3, 10*256);
        sheet.setColumnWidth((short) 4, 10*256);
        sheet.setColumnWidth((short) 5, 15*256);
        sheet.setColumnWidth((short) 6, 50*256);
        sheet.setColumnWidth((short) 7, 50*256);
        
        //创建字体
        Font f0 = wb.createFont();
        f0.setFontHeightInPoints((short) 20);
        f0.setColor(IndexedColors.GREY_25_PERCENT.index);
        f0.setBoldweight(Font.BOLDWEIGHT_BOLD);
        
        // 创建单元格格式
        CellStyle cs0 = wb.createCellStyle();
        cs0.setFont(f0);
        cs0.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs0.setFillForegroundColor(IndexedColors.PLUM.index);
        cs0.setAlignment(CellStyle.ALIGN_CENTER);
        cs0.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs1 = wb.createCellStyle();
        cs1.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs1.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.index);
        cs1.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs2 = wb.createCellStyle();
        cs2.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs2.setFillForegroundColor(IndexedColors.GREY_40_PERCENT.index);
        cs2.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs3 = wb.createCellStyle();
        cs3.setBorderLeft(CellStyle.BORDER_THIN);
        cs3.setBorderRight(CellStyle.BORDER_THIN);
        cs3.setBorderTop(CellStyle.BORDER_THIN);
        cs3.setBorderBottom(CellStyle.BORDER_THIN);
        cs3.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs3.setFillForegroundColor(IndexedColors.GREY_50_PERCENT.index);
        cs3.setAlignment(CellStyle.ALIGN_CENTER);
        cs3.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs4 = wb.createCellStyle();
        cs4.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs4.setFillForegroundColor(IndexedColors.PALE_BLUE.index);
        cs4.setAlignment(CellStyle.ALIGN_CENTER);
        cs4.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs5 = wb.createCellStyle();
        cs5.setFillPattern(CellStyle.SOLID_FOREGROUND);
        cs5.setFillForegroundColor(IndexedColors.PLUM.index);
        cs5.setAlignment(CellStyle.ALIGN_CENTER);
        cs5.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        CellStyle cs6 = wb.createCellStyle();
        cs6.setAlignment(CellStyle.ALIGN_CENTER);
        cs6.setVerticalAlignment(CellStyle.VERTICAL_CENTER);
        
        // 创建第一行
        Row row0 = sheet.createRow((short) 0);
        Cell cell0 = row0.createCell(0); 
        cell0.setCellValue("策划服务预算单");
        cell0.setCellStyle(cs0);
        row0.setHeightInPoints(60);
        sheet.addMergedRegion(CellRangeAddress.valueOf("A1:H1"));
        
        //scheme简述
        StringBuffer schemeStr = new StringBuffer();
        schemeStr.append("方案名称： ");
        schemeStr.append(scheme.getName());
        schemeStr.append("        方案状态：");
        schemeStr.append(scheme.getStatus().getName());
        schemeStr.append("        方案类别：");
        for(int i=0; i<scheme.getTypes().size(); i++){
        	if(i==0)
        		schemeStr.append(scheme.getTypes().get(i).getName());
        	else
        		schemeStr.append(","+scheme.getTypes().get(i).getName());
        }
        
        //创建第二行
        Row row1 = sheet.createRow(1);
        Cell cell1 = row1.createCell(0);
        cell1.setCellValue(schemeStr.toString());
        cell1.setCellStyle(cs2);
        row1.setHeightInPoints(25);
        sheet.addMergedRegion(CellRangeAddress.valueOf("A2:H2"));
        
        //case简述
        StringBuffer caseStr = new StringBuffer();
        caseStr.append("案例名称： "+scheme.getMycase().getTitle());
//        caseStr.append("        案例状态："+scheme.getMycase().getStatus().getName());
        caseStr.append("        案例类别："+scheme.getMycase().getBusinessType().getName());
        SimpleDateFormat df = new SimpleDateFormat("yyyy年MM月dd日 HH时mm分ss秒");
        caseStr.append("        举行时间："+df.format(scheme.getMycase().getEventTime()));
        //创建第三行
        Row row2 = sheet.createRow(2);
        Cell cell2 = row2.createCell(0);
        cell2.setCellValue(caseStr.toString());
        cell2.setCellStyle(cs1);
        row2.setHeightInPoints(25);
        sheet.addMergedRegion(CellRangeAddress.valueOf("A3:H3"));
        
        //创建第四行
        Row row3 = sheet.createRow(3);
        row3.setHeightInPoints(25);
        String columnNames[]={"序号","服务项目","单价","数量","单位","总价","备注","活动布置"};//列名
        for(int i=0;i<columnNames.length;i++){
            Cell cell = row3.createCell(i);
            cell.setCellValue(columnNames[i]);
            cell.setCellStyle(cs3);
        }
        
        //根据预算种类显示所有产品
        Iterator<SchemeProductContainer> conIter = schemeProdCtrs.iterator();
        int staticRow = 3;
        int attributeCount = 1;
        while(conIter.hasNext()){
        	
        	SchemeProductContainer prodContainer = conIter.next();
        	//显示预算种类名
        	int rowNo = attributeCount+staticRow;
            Row attrRow = sheet.createRow(rowNo);
            Cell cell = attrRow.createCell(0);
            cell.setCellValue(prodContainer.getProdAttributeName());
            cell.setCellStyle(cs4);
            attrRow.setHeightInPoints(25);
            String mergeRowNo = "A"+(rowNo+1)+":H"+(rowNo+1);
            sheet.addMergedRegion(CellRangeAddress.valueOf(mergeRowNo));
            attributeCount++;
            
            //显示产品
            List<ProductExt> prodList = prodContainer.getProducts();
            for(int i=0; i<prodList.size(); i++){
            	ProductExt prod = prodList.get(i);
            	Row prodRow = sheet.createRow(rowNo+i+1);
            	prodRow.setHeightInPoints(40);
            	ArrayList prodCellValue = new ArrayList();
            	prodCellValue.add(i+1);
            	prodCellValue.add(prod.getTitle()+"---"+prod.getCategorys().get(0).getName());
            	prodCellValue.add(prod.getCategorys().get(0).getPrice());
            	prodCellValue.add(prod.getProductCount());
            	prodCellValue.add("个");
            	prodCellValue.add((prod.getCategorys().get(0).getPrice()).multiply(new BigDecimal(prod.getProductCount())));
            	prodCellValue.add("");
            	prodCellValue.add(""); 
            	 
            	for(int j=0; j<columnNames.length; j++){
            		Cell prodCell = prodRow.createCell(j);
            		prodCell.setCellStyle(cs6);
            		prodCell.setCellValue(prodCellValue.get(j).toString());
            	}
            	attributeCount++;
            }
            //小计
            Row subtotalRow = sheet.createRow(attributeCount+staticRow);
            subtotalRow.setHeightInPoints(25);
            Cell subtotalCell1 = subtotalRow.createCell(0);
            subtotalCell1.setCellStyle(cs5);
            subtotalCell1.setCellValue("小计");
            Cell subtotalCell2 = subtotalRow.createCell(1);
            subtotalCell2.setCellStyle(cs1);
            subtotalCell2.setCellValue(prodContainer.getSubtotalPrice().toString());
            String mergeRowNo2 = "B"+(attributeCount+staticRow+1)+":H"+(attributeCount+staticRow+1);
            sheet.addMergedRegion(CellRangeAddress.valueOf(mergeRowNo2));
            attributeCount++;
        }
        Row totalRow = sheet.createRow(attributeCount+staticRow);
        totalRow.setHeightInPoints(25);
        Cell totalCell1 = totalRow.createCell(0);
        totalCell1.setCellStyle(cs5);
        totalCell1.setCellValue("总计");
        Cell totalCell2 = totalRow.createCell(1);
        totalCell2.setCellStyle(cs2);
        totalCell2.setCellValue(totalPrice.toString());
        String mergeRowNo3 = "B"+(attributeCount+staticRow+1)+":H"+(attributeCount+staticRow+1);
        sheet.addMergedRegion(CellRangeAddress.valueOf(mergeRowNo3));
        
        return wb;
    }
 
}

**Comment by zfdforever** [comment]
第一行每一列都是“题目+选项”会不会太长了？
