### ISSUE TITLE
在Paper的list页面，点击查询，每次查询的结果都不一样

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#55]
在Paper的list页面，点击查询，每次查询的结果都不一样。

**Comment by LiuSiHeng** [comment]
fixed：由于不同paper的创建时间可能相同，所以改为创建时间相同时，按paper_id 降序排序

**Comment by microlcl** [comment]
Paper list如果选择paper status为published进行查询，页面报500异常。
我创建一个新defect来address it。
先close掉这个defect
