### ISSUE TITLE
我发起的调查与我参与的调查里更新时间貌似不起作用，且在创建调查时更新时间与系统时间不符

### ISSUE THREAD

**Issue by liuxiao8114** [microlcl/mysurvey#58]

**Comment by microlcl** [comment]
这个问题描述的我不是很明白，请仔细说明一下。
如果确是问题，please fix it.
Thanks a lot.

**Comment by liuxiao8114** [comment]
1.新建调查时，更新时间不等于调查创建的时间，这个问题仅存在于访问远程地址，本地调试的时候没有这个问题（服务器系统时间设置？时区？）
2.目前更新时间这一列仅在对草稿的更新时起作用，当调查发布以后这个更新时间无法再被更新（比如当参与人参与调查，调查问卷更新后，这个更新时间依然不变，我发起的调查页面与我参与的调查页面都是如此）

关于2 我查了代码，目前发布后是对Answer作更新，Survey不作处理，so worked as design I think
