### ISSUE TITLE
忘记密码功能第二封邮件收不到

### ISSUE THREAD

**Issue by microlcl** [microlcl/mysurvey#68]
部署到bluemix上后，忘记密码功能第二封邮件收不到。
这个需要仔细check一下，看看是什么原因造成的。
在bluemix上发布的流程可以参考如下wiki:
https://github.com/microlcl/mysurvey/wiki/%E9%83%A8%E7%BD%B2%E5%88%B0bluemix

**Comment by LiuSiHeng** [comment]
经测试发现当使用非IBM邮箱账号，忘记密码功能正常。 如通过QQ邮箱注册，忘记密码邮件收发正常，但是QQ邮箱会把邮件过滤为垃圾邮件。
将邮件服务器改为使用139邮箱进行部署测试，QQ邮箱不会把邮件标为垃圾邮件，但是IBM邮箱账号依然收不到第二封邮件。

**Comment by LiuSiHeng** [comment]
fixed
