### ISSUE TITLE
My Papers的问题

### ISSUE THREAD

**Issue by Glory-Road** [microlcl/mysurvey#69]
点开My Papers，选择Paper Status、Paper Status，然后点击Create Paper，接下来填写Paper Name选择Business Type，然后点击choose questions,填写完question后点击OK，最后点击submit。显示错误页：500 - Internal error occurred.

**Comment by microlcl** [comment]
不能重现。
LiXian，
Please double check.

**Comment by lx650** [comment]
Fixed.
