### ISSUE TITLE
Publish Paper:   500 - Internal error occurred.

### ISSUE THREAD

**Issue by Glory-Road** [microlcl/mysurvey#77]
点击My Papers，首先要建立一个paper，然后点击一个paper的Create Survey，进入到Publish Paper页面。
Paper Subject:随意填写；Deadline:填写一个合格的时间；Survey Groups:全选上，然后点击send paper按钮。  接下来页面会呈现500 - Internal error occurred页面。

**Comment by liuxiao8114** [comment]
经过测试，当不同的group下存在相同的id时会报500的错误，原因是由于insert时survey_receivers表的主键相同所引起，请据此尝试fix

**Comment by Glory-Road** [comment]
fixed
