### ISSUE TITLE
Edit Paper，提交报错

### ISSUE THREAD

**Issue by Glory-Road** [microlcl/mysurvey#79]
删除一些question，然后Edit 只包含删除的问题的paper，这时候之前选择的问题已经被删除了，这个页面也就不存在之前选择的问题了，submit，出现500错误。

**Comment by microlcl** [comment]
另外我发现如下问题：
1. 创建的所有paper都是draft状态。并且此状态之后没有改变了。一个简单发fix方法是： 
基于这个paper发布了一个survey后，那么paper的状态就应该改为published
2. 对于published 状态的paper，不允许修改里面的question。

**Comment by liuxiao8114** [comment]
fixed
