### ISSUE TITLE
导出功能的信息完善

### ISSUE THREAD

**Issue by liuxiao8114** [microlcl/mysurvey#80]
对导出的文件添加以下的信息：
1.未作答的userId的显示。目前只显示了已作答的user。
2.增加group列，以方便调查人员能够清楚区分每个作答的user所对应的group

另外，目前导出的文件没有添加后缀需要手动修改，请增加为.xls格式的文件

**Comment by liuxiao8114** [comment]
Chunlei，关于导出信息的完善如有其他请补充说明，Thanks！

**Comment by microlcl** [comment]
重点fix如下问题（按优先级从高到低）：
1. 导出文件没有后缀名，应该增加.xls为后缀名
2. 导出的内容中， 问题title只有问题本身，应包含选项
3.未作答的userId的显示。目前只显示了已作答的user。
4.增加group列，以方便调查人员能够清楚区分每个作答的user所对应的group

**Comment by LiuSiHeng** [comment]
fixed
