### ISSUE TITLE
提供修改密码功能

### ISSUE THREAD

**Issue by liuxiao8114** [microlcl/mysurvey#82]
在登录后的右上角用户名的button下增加修改密码项，并完善该功能

**Comment by LiuSiHeng** [comment]
Hi LiuXiao, 修改密码功能在MyProfile里已经实现了，如要再加一个修改密码项，请注意把MyProfile里的修改密码功能去掉，Thank You.

**Comment by microlcl** [comment]
是的，这个功能在MyProfile里面已经实现了。
