### ISSUE TITLE
我的群组界面显示

### ISSUE THREAD

**Issue by liuxiao8114** [microlcl/mysurvey#84]
对我的群组界面做如下调整：
1.调整group name后文本框的位置使之与其他的文本框位置左对齐
2."id:"的显示做粗体处理使之与其他文字的表现一致
3.对import按钮的使用追加说明

**Comment by liuxiao8114** [comment]
Chunlei,关于上面的第三项，这个导入的使用感觉不太明确（我在测试的过程中也没有使用成功过），求解。Thanks a lot

**Comment by LiuSiHeng** [comment]
Hi, LiuXiao, 导入功能是指批量导入csv文件， 所以导入的文件需要时csv文件，格式为Nickname,Id。

**Comment by microlcl** [comment]
It's right! Thanks Si Heng for your clarification.

**Comment by lx650** [comment]
fixed. I use the 'controls' class to structured the UI elements.
