### ISSUE TITLE
我创建的调查的被调查组一栏的链接问题

### ISSUE THREAD

**Issue by liuxiao8114** [microlcl/mysurvey#85]
目前这个链接全部跳转到我的调查组的list界面，而不是跳转至选中组的单独成员信息（目前当存在多个调查组时也不能单独选中某个调查组）

**Comment by liuxiao8114** [comment]
Chunlei, please check if this is necessary.Thanks!

**Comment by microlcl** [comment]
这个需要fix一下，可以link到这个group的编辑页面。

**Comment by Glory-Road** [comment]
fixed
