### ISSUE TITLE
My Paticipation 500 Internal error

### ISSUE THREAD

**Issue by lx650** [microlcl/mysurvey#92]
步骤：
1.打开“我参与的调查”
2.选择任意一个调查，点击“查看（可修改）”
3.选择任意一个选项，比如第一个选项，点击提交
4.再次打开这个调查，点击“查看（可修改）”
5.你会发现，默认的选项是之前没有选择的，然后点击提交
问题：
显示500 internal error，
再次点击“查看（可修改）”的时候，依然显示500 internal error

**Comment by gongbf** [comment]
Fixed
